#!/bin/sh

set -e

cleanup() {
    rm -rf "$tmp"
}

# _KBRANCH_GIT is the yocto project kernel git
#
# _KBRANCH is the yocto kernel branch that we use. See
# http://www.yoctoproject.org/docs/2.5/ref-manual/ref-manual.html#var-KBRANCH
#
# _KBRANCH_COMMIT
# This is the (merge) commit to use from KBRANCH
#
# _KBRANCH_GIT_DEPTH
# depth of the git tree to checkout.
#
# This roughly corresponds to poky's do_kernel_checkout task
checkout_yocto_kernel() {
    local _KBRANCH_GIT="https://github.com/2ll2/linux-yocto-${mainkver}.git"
    local _KBRANCH="standard/tiny/base"
    local _KBRANCH_COMMIT="1dffb1104ef723e96a204af53cd5a5ad5f2c1dcb"
    local _KBRANCH_GIT_DEPTH=5
    local saved_pwd=$(pwd -P)

    cd "$tmp"
    git clone -b "$_KBRANCH" --depth "$_KBRANCH_GIT_DEPTH" \
        --single-branch "$_KBRANCH_GIT" linux-yocto

    cd linux-yocto
    git checkout "$_KBRANCH_COMMIT" -b kbranch-commit
    cd "$saved_pwd"
}

# YKC stands for yocto kernel cache
checkout_yocto_kernel_cache() {
    local _YKC_GIT="git://git.yoctoproject.org/yocto-kernel-cache"
    # At this time, upstream does not have yocto-4.14 branch. Therefore we are
    # working off master. We'll revert to yocto-$mainver once yocto-4.14 branch
    # becomes available.
    local _YKC_BRANCH="master"
    local _YKC_COMMIT="ee7e849882aa2f0947dd56a60ba5b0d2eec558f2"
    local saved_pwd=$(pwd -P)

    cd "$tmp"
    git clone -b "$_YKC_BRANCH" --single-branch "$_YKC_GIT" yocto-kernel-cache

    cd yocto-kernel-cache
    git checkout "$_YKC_COMMIT" -b ykc-commit

    # Fix kver due to non-availability of upstream YKC yocto-4.14 branch
    echo "v$fullkver" > kver

    cd "$saved_pwd"
}

# This roughly corresponds to poky's do_kernel_meta task
#
# _KMACHINE
# http://www.yoctoproject.org/docs/2.5/ref-manual/ref-manual.html#var-KMACHINE
#
# _KTYPE
# http://www.yoctoproject.org/docs/2.5/ref-manual/ref-manual.html#var-KTYPE
#
# _KMACHINE and _KTYPE is used to extract out bsp description '.scc' file from
# yocto-kernel-cache
# http://www.yoctoproject.org/docs/2.5/kernel-dev/kernel-dev.html#bsp-descriptions
kernel_meta() {
    local _KMACHINE="qemu_x86_64-dom0"
    local _KTYPE="tiny"
    local _KARCH="x86_64"
    # smp_64.scc is needed for xen.scc. net.scc is required to enable virtio
    # networking. standard.scc's include of vfat.scc does not import vfat.cfg,
    # so we import cfg/fs/vfat.scc here.
    local kmeta_ykc_features_list="
        cfg/smp_64.scc
        cfg/fs/vfat.scc
        features/net/net.scc
        features/debug/debug-kernel.scc
        features/debug/printk.scc
        "
    local kmeta_local_features_list="
        cfg/localversion.scc
        features/fedora/fedora.scc
        features/squashfs/squashfs.scc
        features/xen/xen.scc
        "

    local kmeta_local_dir="$(dirname $0)"
    local kmeta_ykc_dir="$tmp/yocto-kernel-cache"

    local bsp_definition=$(spp -I$kmeta_local_dir -I$kmeta_ykc_dir \
                               --find -DKMACHINE=$_KMACHINE -DKTYPE=$_KTYPE -DKARCH=$_KARCH)
    local meta_dir=$(kgit --meta)

    local kmeta_ykc_features=""
    for i in $kmeta_ykc_features_list; do
        kmeta_ykc_features="$kmeta_ykc_features $i"
    done

    local kmeta_local_features=""
    for i in $kmeta_local_features_list; do
        kmeta_local_features="$kmeta_local_features $i"
    done

    mkdir -p "$tmp/linux-yocto/$meta_dir"
    echo "$bsp_definition" > "$tmp/linux-yocto/$meta_dir/bsp_definition"
    scc --force -o "$tmp/linux-yocto/$meta_dir:cfg,merge,meta" \
        -I$kmeta_local_dir -I$kmeta_ykc_dir \
        $bsp_definition \
        $kmeta_local_features $kmeta_ykc_features
    scc --force -o "$tmp/linux-yocto/$meta_dir:patch" --cmds patch \
        -I$kmeta_local_dir -I$kmeta_ykc_dir \
        $kmeta_local_features $kmeta_ykc_features
}

# This roughly corresponds to poky's do_patch task
apply_patch() {
    local saved_pwd=$(pwd -P)

    cd "$tmp/linux-yocto"
    git config --local user.email lambda2.patch@lambda2
    git config --local user.name Lambda2

    local meta_dir=$(kgit --meta)
    (cd $meta_dir; ln -sf patch.queue series)
    if [ -f "$meta_dir/series" ]; then
        kgit-s2q --gen -v --patches $meta_dir
    fi

    cd "$saved_pwd"
}

# This roughly corresponds to poky's do_kernel_configme task
kernel_configme() {
   local saved_pwd=$(pwd -P)

   cd "$tmp/linux-yocto"
   meta_dir=$(kgit --meta)
   configs="$(scc --configs -o $meta_dir)"

   mkdir -p "$tmp/dot-configdir"
   ARCH=x86_64 merge_config.sh -n -O "$tmp/dot-configdir" $configs > "$tmp/dot-configdir/merge_config_build.log" 2>&1

   cd "$saved_pwd"
}

# Extracts .config and generated patch to /tmp
extract_artifacts() {
    local saved_pwd=$(pwd -P)

    cd "$tmp/dot-configdir/source"
    git diff "v$fullkver" HEAD > /tmp/generated-kernel-patch.patch
    cp "$tmp/dot-configdir/.config" /tmp/config-qemu_x86_64-dom0.x86_64

    cd "$saved_pwd"
}

tmp="$(mktemp -d)"
trap cleanup EXIT

# kernel version
fullkver="4.14.15"
# kernel version without SUBLEVEL
mainkver=${fullkver%.*}

checkout_yocto_kernel

checkout_yocto_kernel_cache

kernel_meta

apply_patch

kernel_configme

extract_artifacts

echo "Generated config-qemu_x86_64-dom0.x86_64 and generated-kernel-patch.patch in /tmp"

echo -n "Cleaning up..."
cleanup
echo "Done!"
